### PR TITLE
Moving NGFC Flowsheet To Examples

### PR DESCRIPTION
**Pull request by bpaul4**
## Fixes # .
- "Revive" a prior version of the NGFC flowsheet example notebook and update the example, files and indexing for recent improvements to the model script.
- Edited some doctree index files to properly run current example (NGFC) and another example (NGCC); the NGCC-SOEC example throws an attribute error while running, and is excluded from the index file for now.

## Proposed changes:
- Original notebook from #18 modified according to updates in https://github.com/IDAES/idaes-pse/pull/836.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by AlexNoring** [comment]
I would like to see this running with the natural gas property package on main. Were you running into trouble with that?

**Comment by bpaul4** [comment]
The notebook runs well with the natural gas properties from idaes-pse main and the SOFC_ROM file in this folder. If we're moving the ROM file here, I'll update the imports now.

**Review by eslickj — COMMENTED** [review]
It looks pretty good, but I don't know much about the model.  What are the changes in the ngcc folder?  Is there something fixed there or was that an accident?

**Comment by bpaul4** [comment]
@eslickj I corrected the NGCC notebook indexing in the `build-ci` or `Flowsheets/index.rst` files, the changes are from that as well as putting images in the correct folder for Sphinx to find.

**Review by AlexNoring — APPROVED** [review]
lgtm

**Review by eslickj — APPROVED** [review]

**Pull request merged**
