### PR TITLE
Adding new reactor notebook examples

### PR DESCRIPTION
**Pull request by bpaul4**
## Proposed changes:
- Reorganized examples-pse/src/Examples/UnitModels to contain subfolders Operations/ and Reactors/
- New plug flow and stoichiometric reactor notebooks and related files in Reactors/
- Associated updates to the build/toctree sources, and translating 1.12.0rc0 updates to appropriate files in Operations/

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@bpaul4 This is a huge pull requests - could you please break it up into smaller pieces so that we can tackle it one unit at a time. Also, are the html files mean to be part of the PR, or are they something that should be generated automatically as part of the docs.?

**Comment by bpaul4** [comment]
I can break it up into three - reorganizing the directories first, and then separating the two notebooks once that is merged. I'll check if the html files should be included.

**Comment by andrewlee94** [comment]
@bpaul4 I think you need to take a deeper look at this PR - you currently have 64 files changed and they look like a lot more than just moving and renaming.

**Comment by bpaul4** [comment]
I believe merging release updates and many resolved merge conflicts added "changes" that are redundant, I'll recreate a cleaner branch. @andrewlee94 would you recommend closing this PR?

**Comment by andrewlee94** [comment]
@bpaul4 That might not be a bad idea at this point. You also have test failures turning up, but at first glance they seemed to be unrelated to this PR.

**Pull request closed without merging**
