### PR TITLE
Change value of temperature fixing by 0.001 to get around solver error in `air_separation_case_study.ipynb` on CentOS 8

### LINKED ISSUE #77: Solver error on CentOS 8 in Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: ValueError: Cannot load a SolverResults object with bad status
```txt
2021-11-30 16:37:22,826 INFO - [Worker 0] Convert notebook name=/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: begin
2021-11-30 16:37:22,826 INFO - [Worker 0] Converting: air_separation_case_study.ipynb
2021-11-30 16:37:23,516 INFO - [Worker 0] Stripped tags from: air_separation_case_study.ipynb
2021-11-30 16:37:23,516 INFO - [Worker 0] Running notebook: air_separation_case_study.ipynb
2021-11-30 16:40:27,235 ERROR - [Worker 0] Notebook execution failed: execution error for '/tmp/tmpb256ax7o/air_separation_case_study.ipynb': An error occurred while executing the following cell:
------------------
m1.fs.F101.heat_duty[0].unfix()
m1.fs.F101.vap_outlet.temperature.fix(77.01)

m1.fs.M101.initialize(outlvl=idaeslog.INFO_LOW) 
propagate_state(m1.fs.s01)
m1.fs.F101.initialize(outlvl=idaeslog.INFO_LOW) 
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_116262/2523001707.py in <module>
      2 m1.fs.F101.vap_outlet.temperature.fix(77.01)
      3 
----> 4 m1.fs.M101.initialize(outlvl=idaeslog.INFO_LOW)
      5 propagate_state(m1.fs.s01)
      6 m1.fs.F101.initialize(outlvl=idaeslog.INFO_LOW)

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/idaes/generic_models/unit_models/mixer.py in initialize(blk, outlvl, optarg, solver, hold_state)
    935             else:
    936                 with idaeslog.solver_log(solve_log, idaeslog.DEBUG) as slc:
--> 937                     res = opt.solve(blk, tee=slc.tee)
    938 
    939             init_log.info(

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/pyomo/opt/base/solvers.py in solve(self, *args, **kwds)
    624                 else:
    625                     if self._load_solutions:
--> 626                         _model.solutions.load_from(
    627                             result,
    628                             select=self._select_index,

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/pyomo/core/base/PyomoModel.py in load_from(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)
    222                     "an 'aborted' status, but containing a solution")
    223             else:
--> 224                 raise ValueError("Cannot load a SolverResults object "
    225                                  "with bad status: %s"
    226                                  % str(results.solver.status))

ValueError: Cannot load a SolverResults object with bad status: error
ValueError: Cannot load a SolverResults object with bad status: error

2021-11-30 16:40:27,235 ERROR - [Worker 0] Execution failed: generating partial output for '/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb'
2021-11-30 16:40:27,235 INFO - [Worker 0] Convert notebook name=/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: end, ok=False duration=184.4s
```

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Fixes #77

As described in #77, a solver error would systematically occur causing the `air_separation_case_study.ipynb` notebook to fail on Cell 21, with the following error message displayed in Cell 19's output:

```txt
>>>result = ipopt.solve(m, tee=False)

WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: infeasible
      - message from solver: Ipopt 3.13.2\x3a Converged to a locally
        infeasible point. Problem may be infeasible.
```

With a shamefully domain-ignorant empirical approach, I tried to change the value used  in the call to `m.fs.F101.vap_outlet.temperature.fix()` to see if it would make a difference, and then plugged in smaller deviations from the original 74 until the existing assertions in Cell 22 passed without modifications.

This seems to solve the original problem described in #77, i.e. the notebook now seems to work just fine on the build system used to build the examples docs. However, I'm deferring to the reviewers and anyone with a deeper understanding of why this is happening to judge whether this is a reasonable fix (pending further investigation), especially to get all examples working for the final 1.12.0 IDAES release, or not.

## UPDATE

I've tested this on two different OSes (CentOS 8 and Ubuntu 20.04) starting in both cases from a vanilla Docker image. The notebook runs just fine in the Ubuntu container, but fails in the same way as described in #77 on the fresh CentOS system. This points in the direction of this being an OS-dependent solver issue, since our build system where the notebook doesn't run also runs CentOS. I've updated the title to reflect this.

## Proposed changes:
- Change value of temperature fixing in Cell 17 by 0.001 to get around solver error on CentOS 8 build system
  - The variation seems to be small enough that the solution still satisfies all existing assertions within tolerance

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
Whilst this solution appears to work, it isn't really addressing the underlying issue of why the model wouldn't solve at the previous point (even though it is very close to the new one). This is not the first time I have seen behaviour like this in these types of models, and it would be really good if we could get to the root cause of it. Also, the fact the @agarciadiego has not been able to reproduce the error is a bit concerning. @bpaul4 would you have time to take a quick look and see if you can reproduce this error for us?

**Comment by agarciadiego** [comment]
@andrewlee94 I was using version1.12.0. I suspect that as with the hydrocarbon example the error is coming from an intermediate log_variable

**Comment by andrewlee94** [comment]
@agarciadiego I suspect the issue might be related to the log variable, but in this case the model is using the initialization routines rather than a json file and then solved for at least one different operating condition before this, so the problem is due to problem formulation rather than just initialization.

**Comment by bpaul4** [comment]
@lbianchi-lbl @andrewlee94 I am not able to reproduce the error on my local machine using IPOPT 3.13, nor do I see this failure occurring in the nightly CI runs on the main repository branch. I also noticed a timeout issue for the DMF_1 notebook on this branch's CI runs that doesn't appear on the main repository CI runs.

**Review by andrewlee94 — APPROVED** [review]
This should be fine as a stop-gap.

**Review by agarciadiego — APPROVED** [review]
LGTM

**Pull request merged**
