### PR TITLE
Adding Separation & Flash Unit Models into Jupyter Notebook

### PR DESCRIPTION
**Pull request by MarcusHolly**
## Proposed changes:
Will add information for the following unit models into jupyter notebook

- [x] Separator
- [x] Flash

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
I'm not quite sure why this warning is appearing because I don't believe I am setting mole fraction bounds anywhere.
image

**Comment by andrewlee94** [comment]
@MarcusHolly You probably need to go through the Separator code to find out where that warning is being triggered - my guess is during creation of the outlets but that is just a guess.

Also, you can find icons for most unit operations here: https://github.com/IDAES/idaes-pse/tree/main/idaes/models/unit_models/icons which you should use in these examples. Notably, Separators are traditionally shown as a triangle, not a square.

**Comment by MarcusHolly** [comment]
@andrewlee94 So the issue is that the bounds are being defined in the property package (https://github.com/IDAES/idaes-pse/blob/main/idaes/models/properties/modular_properties/examples/CO2_H2O_Ideal_VLE.py) and then the FTPx modular properties file is just overwriting these bounds. Is there a simple way/line of code that can mute the bounds from being set in the first place so that this warning isn't displayed?
image

**Comment by andrewlee94** [comment]
The line setting the bounds on mole fractions should be removed from (https://github.com/IDAES/idaes-pse/blob/main/idaes/models/properties/modular_properties/examples/CO2_H2O_Ideal_VLE.py.

**Comment by MarcusHolly** [comment]
So should I open a new PR for this simple change in the IDAES repo? All of the other prop packs are fine (do not include mole_frac_comp in the state bounds).

**Comment by andrewlee94** [comment]
@MarcusHolly Yes, please do (and do a quick check of the others whilst you are there).

**Comment by MarcusHolly** [comment]
Not sure how to go about resolving this one failure... the changes made in the last commit were very minimal and everything worked well before that.

**Comment by andrewlee94** [comment]
@MarcusHolly Looks like the failure was a random one - rerunning the test fixed it.

**Review by bpaul4 — APPROVED** [review]
The notebooks looks good, and time allowing would benefit from more detail in the descriptions after each main heading. I won't hold up merging the PR, though, if @andrewlee94 is happy with it.

**Review by andrewlee94 — APPROVED** [review]

**Review by agarciadiego — APPROVED** [review]

**Pull request merged**
