### PR TITLE
Fix errors in Tutorials/Advanced/ParamEst notebooks

### LINKED ISSUE #24: Build error with examples-pse 1.8.0 in file Tutorials/Advanced/ParamEst/DMF_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
```text
2021-01-13 17:18:01,334 ERROR - [Worker 0] Notebook execution failed: execution error for '/tmp/tmpdz3kfiy4/DMF_for_parameter_estimation_NRTL_using_unit_model_solution.ipynb': An error occurred while executing the following cell:
------------------
# save to DMF
# create resources
name = "BT NRTL est param1"
ds_s1 = _dmf.find_one(name=name)
if not ds_s1:
    ds_s1 = _dmf.new(name=name, desc="Solution for data subset 1", data={'SSE': obj_value_1, 'parameters': 
                                                                         {'tau': {'benzene,toluene': parameters_1["fs.properties.tau[('benzene', 'toluene')]"],
                                                                                  'toluene,benzene': parameters_1["fs.properties.tau[('toluene', 'benzene')]"]}}})
    create_relation(ds_s1, Predicates.derived, ds_splits[0])
name = "BT NRTL est param2"
ds_s2 = _dmf.find_one(name=name)
if not ds_s2:
    ds_s2 = _dmf.new(name=name, desc="Solution for data subset 2", data={'SSE': obj_value_2, 'parameters': 
                                                                         {'tau': {'benzene,toluene': parameters_2["fs.properties.tau[('benzene', 'toluene')]"],
                                                                                  'toluene,benzene': parameters_2["fs.properties.tau[('toluene', 'benzene')]"]}}})

    create_relation(ds_s2, Predicates.derived, ds_splits[1])
# save relations (prints number of objects processed)
_dmf.update()
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-c0f0d12ae577> in <module>
      5 if not ds_s1:
      6     ds_s1 = _dmf.new(name=name, desc="Solution for data subset 1", data={'SSE': obj_value_1, 'parameters': 
----> 7                                                                          {'tau': {'benzene,toluene': parameters_1["fs.properties.tau[('benzene', 'toluene')]"],
      8                                                                                   'toluene,benzene': parameters_1["fs.properties.tau[('toluene', 'benzene')]"]}}})
      9     create_relation(ds_s1, Predicates.derived, ds_splits[0])

KeyError: "fs.properties.tau[('benzene', 'toluene')]"
KeyError: "fs.properties.tau[('benzene', 'toluene')]"

2021-01-13 17:18:01,334 ERROR - [Worker 0] Execution failed: generating partial output for '/home/lbianchi/idaes/examples-pse-rel/src/Tutorials/Advanced/ParamEst/DMF_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb'
```

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Motivation
- Fix the remaining error in `Tutorials/Advanced/ParamEst/DMF_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb` after #31 fixed #24

## Proposed changes
- Extract definition of dmf_params from cell used for testing

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
@dangunter The original error from #23 is fixed, but now that notebook fails with a "kernel died" error:

```txt
====> File: D:\a\examples-pse\examples-pse\src\Tutorials\Advanced\ParamEst\DMF_flash_unit_Model_with_NRTL_solution_testing.ipynb
Unknown error: Kernel died
```

I'll quickly try to run it locally directly to see if I can get more detail out of it.

**Comment by lbianchi-lbl** [comment]
OK, so it seems that the likely cause for the error was a dependency issue due to `DMF_flash_unit_Model_with_NRTL_solution_testing.ipynb` requiring DMF data that is created in `DMF_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb`. I've added a number prefix to the filename and now it seems to be working OK also in the CI runs.

I'll re-trigger the tests in IDAES/idaes-pse#215 and make sure that these were the only remaining issues.

**Review by dangunter — APPROVED** [review]
Looks perfect. Thank you for fixing this.

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
