### PR TITLE
Heat Exchanger 0 D Tutorial

### PR DESCRIPTION
**Pull request by anujad95**
Note - shifting the PR from examples-dev here
IDAES/examples-dev#165

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
Note that the location of this tutorial (or example, as the case may be) will change after PR #4 is merged. Any Jupyter notebook example also needs to be added in the appropriate place in the docs, and in the notebook index (I can help with that part, since it's new and not documented yet)

**Comment by dangunter** [comment]
If you could wait to merge this, and put it in the new location, that would be helpful for me; you could tell me what needs to be clarified, added, or removed from the new instructions in README-developer.md (also in PR #4) for adding a new notebook.

**Comment by jghouse88** [comment]
@anujad95 I have made a couple of edits to this. There was a temperature crossover with the inlet conditions that were specified. While fixing U and A seems to work, unfixing A and fixing the deltaTout did not converge. Something to be looked at but we need to show additional options of fixing different combinations of degrees of freedom.

**Comment by jghouse88** [comment]
Closed and replaced with PR #44

**Pull request closed without merging**
