### PR TITLE
Updating parameter estimation tutorial with new data set

### PR DESCRIPTION
**Pull request by jghouse88**
## Proposed changes:
- Updated the data set for this problem
- Corresponding changes in the testing cells to reflect new values
- Changed initial values for the parameter in the model

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by dangunter — CHANGES_REQUESTED** [review]
This is not something you changed, but looking at it again, I think that since the 2 "DMF" example notebooks form a sequence, we should add a link to the second at the bottom of the first. I ran them both and it works pretty well, though. I can't comment on the numeric changes other than the examples still work.

**Comment by dangunter** [comment]
@jghouse88 while you're in there can you correct the typo at the top of `Tutorials/Advanced/ParamEst/DMF_flash_unit_Model_with_NRTL_solution_testing.ipynb` -- somehow an "i=" slipped into the first sentence after the Note.

**Comment by jghouse88** [comment]
@dangunter I have addressed your comments. The links work after they get built, right?

**Review by dangunter — APPROVED** [review]
Looks good.

**Comment by jghouse88** [comment]
@andrewlee94 or @ksbeattie can you please take a look at this for the second review?

**Review by andrewlee94 — APPROVED** [review]
Looks OK to me.

**Pull request merged**
