### PR TITLE
MatOpt documentation update

### PR DESCRIPTION
**Pull request by xiangyuy**
## Fixes # .
NA

## Proposed changes:
-update citations

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@xiangyuy, is this all the changes needed for this?

**Comment by xiangyuy** [comment]
> @xiangyuy, is this all the changes needed for this?

Yes, that's all the changes on our end. The other minor thing is that we think it would be nice that the "Jupyter Notebook source file" above each notebook example can be color-coded as hyperlinks to be obvious that one can click on them. Thank you!

**Review by ksbeattie — APPROVED** [review]
LGTM

**Review by andrewlee94 — APPROVED** [review]
Looks OK

**Pull request merged**
