### PR TITLE
Data quality control example using Pecos

### PR DESCRIPTION
**Pull request by kaklise**
## Proposed changes:
- Adds example notebook for data quality control using Pecos
- This PR is associated with https://github.com/IDAES/idaes-pse/pull/128

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by eslickj — DISMISSED** [review]
Looks good to me.

**Review by dangunter — CHANGES_REQUESTED** [review]
The Pecos/index.rst file should go in the idaes-pse repo under docs/user_guide/modeling_extensions . You can add a hyperlink in the notebook if you want the user to be able to navigate from here to there; you can also add a hyperlink in that page to the examples page. Both should be to the online version of course.

**Comment by kaklise** [comment]
The idaes-pse repo includes a new section for related packages, documentation related to Pecos is included in doc/related_packages/pecos.rst. This file links to the examples landing page (https://idaes.github.io/examples-pse/latest/index.html).  I'll add a new link from pecos/index.rst in this repo back to the related packages docs in idaes-pse.

**Review by ksbeattie — APPROVED** [review]
LGTM

**Comment by ksbeattie** [comment]
@dangunter a/o @eslickj can one of you re-review this?

**Review by eslickj — APPROVED** [review]

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
