### PR TITLE
Fix soec notebook initialization problem

### PR DESCRIPTION
**Pull request by eslickj**
## Fixes issue #176 

Fixes an initialization problem on the spec notebook.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by dallan-keylogic — APPROVED** [review]
LGTM

**Review by andrewlee94 — APPROVED** [review]

**Comment by lbianchi-lbl** [comment]
It seems the notebook is still failing, even though one of the jobs is being reported as passing which I think is related to #116:

image

**Comment by eslickj** [comment]
@lbianchi-lbl, checking on this error, some change in the last day or so broke this.  I'm looking into it.

**Comment by eslickj** [comment]
Okay, it was @andrewlee94's changes to model serializer that broke this one.  It's my fault for using a default mutable argument, but None means something else.  It will take some thinking to figure out how to properly fix this.

**Comment by eslickj** [comment]
@lbianchi-lbl and @andrewlee94 found the problem was that the broken example was depending on changing the default arg, so the good news is that pylint is finding errors.

**Comment by eslickj** [comment]
I'll keep working this until the tests pass.

**Comment by eslickj** [comment]
This is too complicated to sort out.  I'm just going to go ahead and move the SOFC-IES to publications. I'll close this PR and once everything is in its new home, I'll open a new PR to remove them.

**Pull request closed without merging**
