### PR TITLE
Update scaling to fix failing example notebooks

### LINKED ISSUE #96: Several examples tests failing
There are some examples test failing.  I'm having a hard time sorting out what's failing and how, but I suspect it may have something to do with the doc reorg or updating the Pyomo version.  Not sure who to assign this too, so we can try to update that later.

From doc build:

```
docs_test/Examples/Tools/degeneracy_hunter.rst:234: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:234: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:409: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:409: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:409: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:712: ERROR: Undefined substitution referenced: "residual".
docs_test/Examples/Tools/degeneracy_hunter.rst:712: ERROR: Undefined substitution referenced: "residual".
```

```
docs_test/Examples/Tools/data_management_framework.rst:514: ERROR: Unknown target name: "id".
docs_test/Examples/Tools/data_management_framework.rst:576: ERROR: Unknown target name: "id".
```

```
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
docs_test/Examples/SurrMod/PySMO/PySMO_basics.rst:378: ERROR: Unknown target name: "x".
```

```
TypeError: object NoneType can't be used in 'await' expression
2022-02-14 17:52:01,553 ERROR - [Worker 0] Notebook execution failed: execution error for '/tmp/tmpfbxogeg6/air_separation_case_study.ipynb': An error occurred while executing the following cell:
------------------
m.fs.M101.initialize(outlvl=idaeslog.INFO_LOW) 
propagate_state(m.fs.s01)
m.fs.F101.initialize(outlvl=idaeslog.INFO_LOW)
------------------

---------------------------------------------------------------------------
InitializationError                       Traceback (most recent call last)
/tmp/ipykernel_3865/2171148868.py in <module>
      1 m.fs.M101.initialize(outlvl=idaeslog.INFO_LOW)
      2 propagate_state(m.fs.s01)
----> 3 m.fs.F101.initialize(outlvl=idaeslog.INFO_LOW)

/usr/share/miniconda/envs/examples-pse-dev/lib/python3.8/site-packages/idaes/core/unit_model.py in initialize(blk, state_args, outlvl, solver, optarg)
    659 
    660         if not check_optimal_termination(results):
--> 661             raise InitializationError(
    662                 f"{blk.name} failed to initialize successfully. Please check "
    663                 f"the output logs for more information.")
```

```
 2022-02-14 18:25:50,515 DEBUG - Waiting for 1 processes to finish
2022-02-14 18:26:51,519 DEBUG - Waiting for 1 processes to finish
2022-02-14 18:27:22,356 ERROR - [Worker 0] Failed to convert D:\a\examples-pse\examples-pse\src\Examples\Advanced\CustomProperties\Hydrocarbon_Processing_example.ipynb: timeout for 'C:\Users\RUNNER~1\AppData\Local\Temp\tmprw3iry3j\Hydrocarbon_Processing_example.ipynb': 1280.1595520973206s > 600s
```

### PR DESCRIPTION
**Pull request by bpaul4**
## Fixes # .
- Added scaling to `src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb`
- Updated scaling for `src/Examples/Advanced/CustomProperties/Hydrocarbon_Processing_example.ipynb`

## Proposed changes:
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by bpaul4** [comment]
@andrewlee94 I support a quick fix, given that the notebooks run successfully on my local machine and I can locally run the `pytest` commands with no issues. Given that it is hard to tell which lines in the notebooks throw the failure, and that `test_notebooks` runs everything in the doctree, we could temporarily comment out the `CustomProperties` folder from `build.yml` and `build-ci.yml` to allow the release and do a deeper dive into these issues as time allows. Perhaps one or two other developers could pull the latest commits and run locally to confirm if this is purely an issue with the CI environments?

**Comment by andrewlee94** [comment]
@bpaul4 There are some techniques for running the notebook on different platforms - @lbianchi-lbl can tell you more.

**Comment by bpaul4** [comment]
I am including my local environment `pip list` output in case a package version difference is causing the CI environments to fail for tests where my local environment passes. In the meantime to clear the way for the release, @lbianchi-lbl please let me know if you agree with temporarily commenting out the `CustomProperties` folder in the YML build files or would prefer a more targeted solution.

```
Package                            Version             Location
---------------------------------- ------------------- -------------------------------
absl-py                            0.13.0
addheader                          0.2.3
alabaster                          0.7.12
appdirs                            1.4.4
argon2-cffi                        20.1.0
arrow                              1.1.1
astroid                            2.5.6
astunparse                         1.6.3
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
binaryornot                        0.4.4
black                              21.7b0
bleach                             3.3.0
brotlipy                           0.7.0
bunch                              1.0.1
cachetools                         4.2.2
certifi                            2021.10.8
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
colorama                           0.4.4
conda                              4.11.0
conda-package-handling             1.7.2
cookiecutter                       1.7.3
coverage                           5.5
cryptography                       3.2.1
cycler                             0.10.0
debugpy                            1.3.0
decorator                          4.4.2
defusedxml                         0.7.1
diff-match-patch                   20200713
docutils                           0.17.1
entrypoints                        0.3
et-xmlfile                         1.1.0
flake8                             3.9.2
Flask                              2.0.1
Flask-Cors                         3.0.10
flatbuffers                        1.12
fpdf2                              2.4.3
gast                               0.4.0
google-auth                        1.32.1
google-auth-oauthlib               0.4.4
google-pasta                       0.2.0
grpcio                             1.34.1
h5py                               3.1.0
idaes-examples                     1.11.0
idaes-pse                          1.12.0.dev0         c:\users\bpaul\github\idaes-pse
idna                               2.10
imagesize                          1.2.0
importlib-metadata                 4.6.4
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          6.0.1
ipython                            7.25.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.9.1
itsdangerous                       2.0.1
jedi                               0.18.0
Jinja2                             3.0.1
jinja2-time                        0.2.0
joblib                             1.0.1
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.7.1
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.6
jupyter-nbextensions-configurator  0.4.1
jupyterlab-pygments                0.1.2
jupyterlab-widgets                 1.0.0
keras                              2.7.0
keras-nightly                      2.5.0.dev2021032900
Keras-Preprocessing                1.1.2
keyring                            23.1.0
kiwisolver                         1.3.1
lazy-object-proxy                  1.6.0
libclang                           12.0.0
lxml                               4.6.3
Markdown                           3.3.4
MarkupSafe                         2.0.1
matplotlib                         3.4.2
matplotlib-inline                  0.1.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mpmath                             1.2.1
mypy-extensions                    0.4.3
nbclient                           0.5.3
nbconvert                          6.1.0
nbformat                           5.1.3
nest-asyncio                       1.5.1
networkx                           2.5.1
notebook                           6.4.0
numpy                              1.21.5
numpydoc                           1.1.0
oauthlib                           3.1.1
omlt                               0.3.0
openpyxl                           3.0.7
opt-einsum                         3.3.0
packaging                          21.0
pandas                             1.3.0
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.8.2
pathspec                           0.9.0
pecos                              0.2.0
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.3.0
Pint                               0.17
pip                                20.2.4
pluggy                             0.13.1
ply                                3.11
pockets                            0.9.1
poyo                               0.5.0
prometheus-client                  0.11.0
prompt-toolkit                     3.0.19
protobuf                           3.17.3
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.20
pydocstyle                         6.1.1
pyflakes                           2.3.1
Pygments                           2.9.0
pylint                             2.8.3
pyls-spyder                        0.4.0
PyNaCl                             1.4.0
Pyomo                              6.2
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
PyQt5                              5.12.3
PyQt5-sip                          12.9.0
PyQtWebEngine                      5.12.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             6.2.4
pytest-cov                         2.12.1
python-dateutil                    2.8.1
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.1
python-slugify                     5.0.2
pytz                               2021.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           1.1.3
PyYAML                             5.4.1
pyzmq                              22.1.0
QDarkStyle                         3.0.2
qstylizer                          0.2.1
QtAwesome                          1.0.3
qtconsole                          5.1.1
QtPy                               1.9.0
rbfopt                             4.2.2
regex                              2021.8.3
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.19.0
rsa                                4.7.2
Rtree                              0.9.7
ruamel-yaml                        0.15.87
scikit-learn                       0.24.2
scipy                              1.7.0
Send2Trash                         1.7.1
setuptools                         50.3.1.post20201107
six                                1.15.0
sklearn                            0.0
snowballstemmer                    1.2.1
sortedcontainers                   2.4.0
Sphinx                             4.0.3
sphinx-argparse                    0.2.5
sphinx-rtd-theme                   0.5.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-napoleon             0.7
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
spyder                             5.1.1
spyder-kernels                     2.1.0
sympy                              1.8
tensorboard                        2.7.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.0
tensorflow                         2.7.0
tensorflow-estimator               2.7.0
tensorflow-io-gcs-filesystem       0.23.1
termcolor                          1.1.0
terminado                          0.10.1
testpath                           0.5.0
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.2.0
three-merge                        0.1.1
tinycss2                           1.1.0
tinydb                             4.5.0
toml                               0.10.2
tomli                              1.2.1
tornado                            6.1
tqdm                               4.51.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.1.0
urllib3                            1.25.11
watchdog                           2.1.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           2.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
wincertstore                       0.2
wrapt                              1.12.1
yapf                               0.31.0
zipp                               3.5.0
```

**Comment by lbianchi-lbl** [comment]
@bpaul4 Sorry for the delay, I'm picking this back up. A few things:

- As I understand, the notebooks seem to work in your local environment. Other than `pip list` (which is also useful), could you also post the output of `idaes environment-info`? (you might need to run `pip install click==8` before that)
- I hear you about the overhead of testing the notebooks with pytest. One alternative that could possibly work better is using the `build.py` script directly by running `python build.py --verbose --test` from the root of the repository: this will run the notebooks without 
  - You could also comment out all directories in the YAML config file you're using (which you can specify to `build.py` as `--config your-config-file.yml`) and only leave those directories with the notebook(s) you want to run
- If being able to run the notebooks in an interactive Linux environment could be helpful for you, there is a way to do so with Binder (https://mybinder.org) which is what I believe @andrewlee94 was alluding to. The simplest way is probably for me to merge #91 in, so you can then merge the changes back from `main`

**Comment by bpaul4** [comment]
Running `idaes environment-info` gives an error message, and installing `click 8` does not resolve this:

```
Traceback (most recent call last):
  File "C:\Users\bpaul\Miniconda3\Scripts\idaes-script.py", line 33, in <module>
    sys.exit(load_entry_point('idaes-pse', 'console_scripts', 'idaes')())
  File "C:\Users\bpaul\Miniconda3\Scripts\idaes-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\bpaul\Miniconda3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\bpaul\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\bpaul\github\idaes-pse\idaes\commands\__init__.py", line 18, in <module>
    from idaes.commands.base import command_base as cb
  File "c:\users\bpaul\github\idaes-pse\idaes\commands\base.py", line 79, in <module>
    def command_base(verbose, quiet):
  File "C:\Users\bpaul\Miniconda3\lib\site-packages\click\decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "C:\Users\bpaul\Miniconda3\lib\site-packages\click\decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "C:\Users\bpaul\Miniconda3\lib\site-packages\click\core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

The most recent commit above resolved the air separation notebook error by allowing try/except, and successfully regenerated the HC initialization file (although this didn't seem to help reduce the runtime at all). I added scaling factors to the HC notebook for flow, temperature, pressure and mole fractions, and updated fixed mole fractions from 0 to 1e-6. The doc builds now pass, as well as the Linux build examples tests, but all three Windows build examples tests are failing now (only 3.8 failed before). The notebooks run fine locally and take about half an hour each to fully run all solve statements.

Unless @andrewlee94 has thoughts on further scaling, it may be best to skip testing this notebook to shorten the CI run time and avoid holding up other PRs. I let it run overnight and generating the initialization file required 5 hours of runtime, 4.5 hours of which was just initializing the Flash unit `F101`. From looking at the property packages it's unclear why it takes so long to initialize that unit.

**Comment by lbianchi-lbl** [comment]
@bpaul4 That's unexpected to me, that exact error should be caused by a backwards-incompatible change in Click 8.0, so if occurs, it might mean that the version of Click installed in that environment is not 8. Can you run this command to confirm? `python -c "import sys, click; print(sys.executable, click.__version__, sep='\n')"` (this is not critical for the task at hand, but might be good to look into to prevent issues with your dev environment down the line)

As for the notebooks, I certainly don't have any objections to skip them for the time being for the sake of the release, at the very least until other PRs in `examples-pse` being held back by this can be properly tested and merged. If @andrewlee94 agrees, I'd comment out the line with the offending notebooks in the YAML config files with a link to #96 and then merge this in once the rest of the notebooks pass the tests.

**Comment by andrewlee94** [comment]
I really don't want to drop these (especially seeing as they are user facing examples), but we might need to at this rate. If they are taking that long to run, then there are serious issues that need to be resolved however.

To get other things passing, we should probably drop these temporarily (so that we can continue merging other things for the release), but we should try to resolve these issue for the release if possible. @bpaul4 You might want to look at the  HDA example with distillation to see what was done there - it was recently updated with better scaling so there might be something of use there. Also, as these are concrete example cases, we can get away with hard coding scaling factors if need be (i.e. don't feel constrained to use only the automated tools - you can directly set any scaling factor or transform a constraint if it makes things work better).

**Comment by lbianchi-lbl** [comment]
@bpaul4 I agree, that's a good suggestion. I'll do so and in the meantime we can continue iterating on this PR.

`pip install -U idaes-pse` is usually enough when IDAES is installed in site-packages/"user" mode, but it wouldn't work here as it uses the latest version of the code available on PyPI rather than the one from the local Git repository. There are ways to update a developer/editable installation in-place, but, unless there are strong motivations that would make it unfeasible, creating a new Conda environment is the quickest and less gotcha-prone option:

```sh
# from the root of the local clone of the `idaes-pse` repository
conda create -n env-for-examples-pse-100 python=3.8 && conda activate env-for-examples-pse-100
pip install -r requirements-dev.txt
idaes --version
idaes get-extensions
```

**Comment by bpaul4** [comment]
Current iteration of scaling is implemented in #110 and this pull request will be closed.

**Pull request closed without merging**
